### ISSUE TITLE
Rotating schedules

### ISSUE THREAD

**Issue by bradtn** [Midiel/Patrol-Shift-Bid-Scheduler-V2#5]
Any idea how to use system in order to bid on a rotating schedule of varying hours and days off? System appears to only be able to handle static week

**Comment by Midiel** [comment]
V2 only supports static weeks schedule. A work around could be to make multiple bidding schedules with different week hours?

**Comment by bradtn** [comment]
How could we make this happen? I deal with 4-6month long schedules with varying days off and hours how or what adjustment could be made please and thank you
