### ISSUE TITLE
Licensing Status?

### ISSUE THREAD

**Issue by EagleAglow** [Midiel/Patrol-Shift-Bid-Scheduler-V2#9]
Greetings!
I am a beginner with LARAVEL and I am considering using (and/or modifying) portions of this project to begin a new project.  Please consider adding a license statement to clarify how or if this code can be shared.  Thank You!

See: https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by Midiel** [comment]
License added. See installation instructions here https://seniorproject.cis.fiu.edu/seniorprojects/patrol-shift-bid-scheduler-2-0/
